spring:
  profiles: default
  data:
    mongodb:
      uri: mongodb://localhost/risk
server:
  port: 30001
  #port: ${PORT:${SERVER_PORT:0}}
version: 0.0.1
kafka:
  server: localhost:9092
  topic:
    intradayriskset: IntraDayRiskSet
    intradayrisktick: IntraDayRiskTick
    intradaytrade: IntraDayTrade
    calccontext: CalculationContext
    market: MarketEnv
zookeeper:
    server: zookeepr.kafka.svc.cluster.local:2181
com:
  google:
    projectId: gm-repbus-lab-ph7xs