spring:
  profiles: default
  data:
    mongodb:
      uri: mongodb://localhost/risk
server:
  port: 30001
  #port: ${PORT:${SERVER_PORT:0}}
version: 0.0.1
kafka:
  server: localhost:9092
  topic:
    intradayriskset: IntraDayRiskSet
    intradayrisktick: IntraDayRiskTick
    calccontext: CalculationContext
    market: Market
